#' Collects parameter section
#'
#' Outputs list of all non-empty lines specified in parameter section
#'
#' @param rscript line by line list produced from R file for replication
#' @param start an integer specifying the index value in script at which the data section starts
#' @param end an integer specifying the index value in script at which the data section ends
getparams <- function(script, start, end) {
  if(end > start) {
    params <- script[start:end]
    params <- gsub(" ", "", params)
    empties <- which(params == '')
    if(length(empties) > 0) params <- params[-empties]
    params
  }
  else NA
}

#' Loops through parameter creation
#'
#' Main parameter creation function that loops through each line given by getparams()
#' and enlarges the parameter list so there is a unique value for each group. 
#'
#' @param allparams list generated by getparams() of all lines expected to contain parameters
#' @param ngrps number of unique solution sets to produce
#' @param cc_rfile location of output file to be written to during replication process
createallparams <- function(allparams, ngrps, cc_rfile) {
  cat('\n\n# =================================================#',
      '\n# PARAMS: ALL NON-FIXED PARAMETERS',
      '\n# =================================================#', file = cc_rfile, append=T)
  if(sum(is.na(allparams)) == 0) {
    param.names <- rep(NA, length(allparams))
    for(i in 1:length(allparams)) {
      param.names[i] <- createparam(allparams[i], ngrps, cc_rfile)
    }
    if(sum(is.na(param.names)) < length(allparams)) param.names[!is.na(param.names)]
    else NA
  }
  else NA
}

#' Writes to camcon script a new list of parameters of length equal to the number of groups
#'
#' Overwrites the original parameter vector with a new vector of length equal to the number of groups
#' so that individuals groups have original parameter values
#'
#' @param param a single line generated by getparams() that contains the parameter
#' @param ngrps number of unique solution sets to produce
#' @param cc_rfile location of output file to be written to during replication process
createparam <- function(param, ngrps, cc_rfile) {
  param.len <- nchar(param)
  if(length(grep('<-', param)) > 0) {
    pos <- regexpr('<-',param)[1]
    lhs <- substr(param, 1, pos-1)
    rhs <- substr(param, pos+2, param.len)
  }
  if(!exists('lhs') & !exists('rhs') & (length(grep('=', param)) > 0)) {
    pos <- regexpr('=',param)[1]
    lhs <- substr(param, 1, pos-1)
    rhs <- substr(param, pos+1, param.len)
  }
  if(exists('lhs') & exists('rhs')) {
    par <- eval(parse(text=rhs))
    if(length(par) == ngrps) cat('\n',param, sep='', file = cc_rfile, append=T)
    if(length(par) > ngrps) cat('\n',param,'[1:',ngrps,']', sep='', file = cc_rfile, append=T)
    if(length(par) < ngrps) cat('\n',lhs,' <- unlist(sapply(1:',ngrps,', function(i) ',rhs,'))[1:',ngrps,']',sep='', file = cc_rfile, append=T)
  }
  if(exists('lhs')) lhs
  else NA
}